name: build-windows
on: 
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: Select a Windows version
        default: windows-2022
        required: true
        options: 
          - windows-latest
          - windows-2025
          - windows-2022

jobs:
  build:
    runs-on: ${{ inputs.os }}

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - uses: benjlevesque/short-sha@v3.0
      # id: short-sha

    - name: build chuck
      run: make

    - uses: actions/upload-artifact@v4
      with:
        name: chuck-max-windows-amd64-${{ env.SHA }}
        path: |
            externals
            help
            examples
            patchers
            support
            LICENSE
            README.md
            package-info.json
