name: demo
on: [workflow_dispatch]

jobs:
  demo_windows:
    runs-on: windows-2022
    steps:

    - name: echo variables
      run: |
      	echo "GITHUB_ACTION: ${{ github.action }}"
      	echo "GITHUB_ACTION_PATH: ${{ github.action_path }}"
      	echo "GITHUB_ACTOR: ${{ github.actor }}"
      	echo "GITHUB_JOB: ${{ github.job }}"
      	echo "GITHUB_REF: ${{ github.ref }}"
        echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
        echo "GITHUB_REPOSITORY: ${{ github.repository }}"
        echo "GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}"
        echo "GITHUB_SHA: ${{ github.sha }}"
