name: demo
on: [workflow_dispatch]

jobs:
  one:
    runs-on: ubuntu-latest
    steps:

      # - name: get pkg name
      #   id: strings
      #   shell: bash
      #   run: echo "pkg_name=${{ github.event.repository.name }}-${{ github.ref_name }}-${{ runner.os }}-${{ runner.arch }}" >> "$GITHUB_OUTPUT"

      - name: get pkg name in python
        id: strings
        shell: python
        run: |
          import os
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            name="${{ github.event.repository.name }}-${{ github.ref_name }}-${{ runner.os }}-${{ runner.arch }}"
            f.write(f"pkg_name={name.lower()}\n")

      - name: dump pkg name
        run: echo "${{ steps.strings.outputs.pkg_name }}"
