name: demo
on: [workflow_dispatch]

jobs:
  demo_windows:
    runs-on: windows-2022
    steps:

    - name: echo variables
      run: |
      	echo "GITHUB_ACTION: $GITHUB_ACTION"
      	echo "GITHUB_ACTION_PATH: $GITHUB_ACTION_PATH"
      	echo "GITHUB_ACTOR: $GITHUB_ACTOR"
